[package]
name = "discord-frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
serenity = "0.12"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
tracing.workspace = true
tracing-subscriber = "0.3.20"
