[workspace]
resolver = "3"
members = ["discord-frontend" , "files-module", "gdrive-module", "search-master"]
exclude = []

[workspace.dependencies]
files-module.path = "files-module"
tracing = "0.1.41"

serde = "1.0.228"

[profile.release]
strip = false
debug = true
