[package]
name = "files-module"
version = "0.1.0"
edition = "2024"

[dependencies]
docx-rust = "0.1.10"
pdf-extract = "0.10.0"
tracing.workspace = true
search-master-interface.workspace = true
walkdir = "2.5.0"
